@DientesLimpios.API_HostAddress = https://localhost:7241/api/consultorios
GET {{DientesLimpios.API_HostAddress}}/019cb9fb-eace-7a3c-957d-91567f9acc7d
Accept: application/json
Authorization: Bearer CfDJ8HOt0HtFyLFOsDUxFkNx0_9btauQsDvxH1XlBbkwM38TM05S3W5py51i3aJ4k_qu_87mfnlQsASDfK7i6zNUOG8nk1A0iYPx9gUlZEXEXC_g2g-RFEWQtKLwBMw895efyAuGLX7MbpAUB15aglzYTf7ApBVhs4yLr0Zus5GjWl7Gv6QvLBk6qIXnctms6jbBy_y7ntxmL5lmqm6eTKzJWNvLaDSPwX8hxjYtoPyC5B-oULs6W4oFK252ELhCW6m1039bLzKIwpBlSqHpCXEUca9ukUr0WEQvArYgas5ykLtbO_JPN_8ym5gt3jEOt-rlYioteXsVVS6FKN0Q6YlKQ5ZuF9_XqJLyw8NvUqojfrbLx0uU-XcvOFrZSdhzUtQfBaiO7ZhR5DZwCzs6oFUPbFF0zJ-3I8O37SoMETJbIfI4yjZ_zZ-cefCbV6Nnshk6dHBbVv5RNNoEkY8gXGC3fw0FG9lwjFRwbLPfibi6ODoK--wX0x3pgrS8u0qUvRPO9W-kPxTuEdVJp5QFgsOZFHHEcqt3XJP5L3VdvSvIL4EZboeIb9xpB2DDds4DWR22q7pZscmey185VrNJxf3Wxpz2nXj-foSI7icBqLGbUUIj8DtsHpYkT9BmQ9qZqxgXr4CJqpKU55Qw8h2vySzaO_uVUuZxhzNqOm9BnWZY8fRFMeUgxbRUr4_8RcZuIoBy-TMKorZG42YogRxbPojNa0Kx1UjcvmS9BFDk2WCxTY4v

###

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8HOt0HtFyLFOsDUxFkNx0_9btauQsDvxH1XlBbkwM38TM05S3W5py51i3aJ4k_qu_87mfnlQsASDfK7i6zNUOG8nk1A0iYPx9gUlZEXEXC_g2g-RFEWQtKLwBMw895efyAuGLX7MbpAUB15aglzYTf7ApBVhs4yLr0Zus5GjWl7Gv6QvLBk6qIXnctms6jbBy_y7ntxmL5lmqm6eTKzJWNvLaDSPwX8hxjYtoPyC5B-oULs6W4oFK252ELhCW6m1039bLzKIwpBlSqHpCXEUca9ukUr0WEQvArYgas5ykLtbO_JPN_8ym5gt3jEOt-rlYioteXsVVS6FKN0Q6YlKQ5ZuF9_XqJLyw8NvUqojfrbLx0uU-XcvOFrZSdhzUtQfBaiO7ZhR5DZwCzs6oFUPbFF0zJ-3I8O37SoMETJbIfI4yjZ_zZ-cefCbV6Nnshk6dHBbVv5RNNoEkY8gXGC3fw0FG9lwjFRwbLPfibi6ODoK--wX0x3pgrS8u0qUvRPO9W-kPxTuEdVJp5QFgsOZFHHEcqt3XJP5L3VdvSvIL4EZboeIb9xpB2DDds4DWR22q7pZscmey185VrNJxf3Wxpz2nXj-foSI7icBqLGbUUIj8DtsHpYkT9BmQ9qZqxgXr4CJqpKU55Qw8h2vySzaO_uVUuZxhzNqOm9BnWZY8fRFMeUgxbRUr4_8RcZuIoBy-TMKorZG42YogRxbPojNa0Kx1UjcvmS9BFDk2WCxTY4v

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8HOt0HtFyLFOsDUxFkNx0_9btauQsDvxH1XlBbkwM38TM05S3W5py51i3aJ4k_qu_87mfnlQsASDfK7i6zNUOG8nk1A0iYPx9gUlZEXEXC_g2g-RFEWQtKLwBMw895efyAuGLX7MbpAUB15aglzYTf7ApBVhs4yLr0Zus5GjWl7Gv6QvLBk6qIXnctms6jbBy_y7ntxmL5lmqm6eTKzJWNvLaDSPwX8hxjYtoPyC5B-oULs6W4oFK252ELhCW6m1039bLzKIwpBlSqHpCXEUca9ukUr0WEQvArYgas5ykLtbO_JPN_8ym5gt3jEOt-rlYioteXsVVS6FKN0Q6YlKQ5ZuF9_XqJLyw8NvUqojfrbLx0uU-XcvOFrZSdhzUtQfBaiO7ZhR5DZwCzs6oFUPbFF0zJ-3I8O37SoMETJbIfI4yjZ_zZ-cefCbV6Nnshk6dHBbVv5RNNoEkY8gXGC3fw0FG9lwjFRwbLPfibi6ODoK--wX0x3pgrS8u0qUvRPO9W-kPxTuEdVJp5QFgsOZFHHEcqt3XJP5L3VdvSvIL4EZboeIb9xpB2DDds4DWR22q7pZscmey185VrNJxf3Wxpz2nXj-foSI7icBqLGbUUIj8DtsHpYkT9BmQ9qZqxgXr4CJqpKU55Qw8h2vySzaO_uVUuZxhzNqOm9BnWZY8fRFMeUgxbRUr4_8RcZuIoBy-TMKorZG42YogRxbPojNa0Kx1UjcvmS9BFDk2WCxTY4v
{
  "nombre": "Consultorio B"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019dd602-dbf5-77a6-8ec4-ee00456e9b72
Content-Type: application/json
Authorization: Bearer CfDJ8HOt0HtFyLFOsDUxFkNx0_9btauQsDvxH1XlBbkwM38TM05S3W5py51i3aJ4k_qu_87mfnlQsASDfK7i6zNUOG8nk1A0iYPx9gUlZEXEXC_g2g-RFEWQtKLwBMw895efyAuGLX7MbpAUB15aglzYTf7ApBVhs4yLr0Zus5GjWl7Gv6QvLBk6qIXnctms6jbBy_y7ntxmL5lmqm6eTKzJWNvLaDSPwX8hxjYtoPyC5B-oULs6W4oFK252ELhCW6m1039bLzKIwpBlSqHpCXEUca9ukUr0WEQvArYgas5ykLtbO_JPN_8ym5gt3jEOt-rlYioteXsVVS6FKN0Q6YlKQ5ZuF9_XqJLyw8NvUqojfrbLx0uU-XcvOFrZSdhzUtQfBaiO7ZhR5DZwCzs6oFUPbFF0zJ-3I8O37SoMETJbIfI4yjZ_zZ-cefCbV6Nnshk6dHBbVv5RNNoEkY8gXGC3fw0FG9lwjFRwbLPfibi6ODoK--wX0x3pgrS8u0qUvRPO9W-kPxTuEdVJp5QFgsOZFHHEcqt3XJP5L3VdvSvIL4EZboeIb9xpB2DDds4DWR22q7pZscmey185VrNJxf3Wxpz2nXj-foSI7icBqLGbUUIj8DtsHpYkT9BmQ9qZqxgXr4CJqpKU55Qw8h2vySzaO_uVUuZxhzNqOm9BnWZY8fRFMeUgxbRUr4_8RcZuIoBy-TMKorZG42YogRxbPojNa0Kx1UjcvmS9BFDk2WCxTY4v
{
  "nombre": "Consultorio B - Actualizado"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/01988492-0a91-7940-b9e3-2a7f4a59b81e
Accept: application/json