@DientesLimpios.API_HostAddress = https://localhost:7241
POST {{DientesLimpios.API_HostAddress}}/register
Content-Type: application/json

{
  "email": "felipe@ejemplo.com",
  "password": "aA123456!"
}

###

POST {{DientesLimpios.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "felipe@ejemplo.com",
  "password": "aA123456!"
}